apiVersion: v1
kind: Pod
metadata: 
  name: api-js
  labels:
    app: api-js
spec:
  containers:
    - name: api-node-js
      image: plobon/api-node-js:1.0
      env: 
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: config-map-database
              key: DATABASE_HOST
      ports:
        - containerPort: 3000
      resources:
        limits:
          memory: "512Mi"
          cpu: "1"
        requests:
          memory: "256Mi"
          cpu: "0.2"



# caso eu queira usar o arquivo inteiro
# envFrom:
# - configMapRef:
#     name: db-configmap
